[package]
name = "token-vesting"
version = "0.1.0"
authors = ["Alex Sakai <bestlucky1030@gmail.com>"]
edition = "2022"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-program = "1.5.0"
